version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: francescoxx/node_live_app
    ports:
      - "8000:8000"
    environment:
      - PG_DB=rent_node_db
      - PG_USER=hadia
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db
    volumes:
      - ./tests:/tests   # Mapping the tests directory into the container

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rent_node_db
      - POSTGRES_USER=hadia
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data_v:/var/lib/postgresql/data

volumes:
  node_db_data_v: {}