apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-db
  template:
    metadata:
      labels:
        app: node-db
    spec:
      containers:
      - name: node-db
        image: postgres:12
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: rent_node_db
        - name: POSTGRES_USER
          value: hadia
        - name: POSTGRES_PASSWORD
          value: "12345"  # Enclose the value in quotes to ensure it's interpreted as a string
      volumes:
      - name: node-db-data-volume
        emptyDir: {}
